export const VERSION_ARRAY = [
  'shield',
  'sword',
  'lets-go-eevee',
  'lets-go-pikachu',
  'ultra-moon',
  'ultra-sun',
  'moon',
  'sun',
  'alpha-sapphire',
  'omega-ruby',
  'y',
  'x',
  'white-2',
  'black-2',
  'xd',
  'colosseum',
  'white',
  'black',
  'soulsilver',
  'heartgold',
  'platinum',
  'pearl',
  'diamond',
  'leafgreen',
  'firered',
  'emerald',
  'sapphire',
  'ruby',
  'crystal',
  'silver',
  'gold',
  'yellow',
  'blue',
  'red',
];

export const VERSION_GROUP_ARRAY = [
  'sword-shield',
  'lets-go-pikachu-lets-go-eevee',
  'ultra-sun-ultra-moon',
  'sun-moon',
  'omega-ruby-alpha-sapphire',
  'x-y',
  'black-2-white-2',
  'xd',
  'colosseum',
  'black-white',
  'heartgold-soulsilver',
  'platinum',
  'diamond-pearl',
  'firered-leafgreen',
  'emerald',
  'ruby-sapphire',
  'crystal',
  'gold-silver',
  'yellow',
  'red-blue',
];

export const VERSION_TO_GENERATION: Record<string, number> = {
  red: 1,
  blue: 1,
  yellow: 1,
  gold: 2,
  silver: 2,
  crystal: 2,
  ruby: 3,
  sapphire: 3,
  emerald: 3,
  firered: 3,
  leafgreen: 3,
  diamond: 4,
  pearl: 4,
  platinum: 4,
  heartgold: 4,
  soulsilver: 4,
  black: 5,
  white: 5,
  colosseum: 3,
  xd: 3,
  'black-2': 5,
  'white-2': 5,
  x: 6,
  y: 6,
  'omega-ruby': 6,
  'alpha-sapphire': 6,
  sun: 7,
  moon: 7,
  'ultra-sun': 7,
  'ultra-moon': 7,
  'lets-go-pikachu': 7,
  'lets-go-eevee': 7,
  sword: 8,
  shield: 8,
};

export const VERSION_GROUP_TO_GENERATION: Record<string, number> = {
  'red-blue': 1,
  yellow: 1,
  'gold-silver': 2,
  crystal: 2,
  'ruby-sapphire': 3,
  emerald: 3,
  'firered-leafgreen': 3,
  'diamond-pearl': 4,
  platinum: 4,
  'heartgold-soulsilver': 4,
  'black-white': 5,
  colosseum: 3,
  xd: 3,
  'black-2-white-2': 5,
  'x-y': 6,
  'omega-ruby-alpha-sapphire': 6,
  'sun-moon': 7,
  'ultra-sun-ultra-moon': 7,
  'lets-go-pikachu-lets-go-eevee': 7,
  'sword-shield': 8,
};
